baseURL = "https://renanbirck.rocks/"
languageCode = "en-us"
title = "TÃ³picos AvanÃ§ados em Temas AleatÃ³rios"
theme = "newsroom"
author = "Renan Birck Pinheiro"
copyright = "Copyright Â© 2022- Renan Birck Pinheiro. Todos os direitos reservados."
paginate = 4

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true # preciso para embutir HTML bruto
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2

[params]
  [params.designer]
    name = "Renan Birck Pinheiro"
    url = "https://www.linkedin.com/in/renanbirck/"
  [[params.authors]]
    name = "renan" # can be nickname # if fullName ğŸ‘‡ğŸ» isn't set, name will be displayed on author card
    fullName = "Renan Birck Pinheiro" # optional. If set, it will display on author card
    bio = "Apenas mais alguÃ©m tentando criar um canto nessa tal de internet."
    photo = "myPhotoFile.jpg"
    url = "https://renanbirck.rocks/"
    twitter = "@birckrenan"

[menu]
  [[menu.main]]
    name = "Sobre"
    url = "about/"
    weight = 2
  [[menu.main]]
    name = "Categorias"
    url = "categories/"
    weight = 3
  [[menu.main]]
    name = "Fale comigo..."
    url = "contact/"
    weight = 4
